env:
  matrix:
    - SCHEME="ChezScheme"
    - SCHEME="Guile"
    - SCHEME="Racket"
    - SCHEME="Sagittarius"
    - SCHEME="Vicare"

matrix:
  allow_failures:
    - env: SCHEME="Guile"
    - env: SCHEME="Racket"
    - env: SCHEME="Sagittarius"
  fast_finish: true

addons:
  apt:
    packages:
      - racket
      - guile-2.0
      # For Vicare
      - libgmp-dev

language: c

cache: ccache

os:
  - linux

compiler:
  - gcc

before_script:
  # Install machine-code
  - wget https://github.com/weinholt/machine-code/archive/master.zip -O machine-code-master.zip
  - unzip machine-code-master.zip
  - mkdir -p external && mv machine-code-master external/machine-code
  - export SCHEME_LIBRARY_PATH=$PWD/external
  # XXX: The build-scheme script should be moved to a different repo.
  - set -o pipefail && eval "$(external/machine-code/build-scheme.sh $SCHEME)"

script:
  - ./run-tests.sh
